CREATE TABLE users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY ,
  username VARCHAR(80) NOT NULL UNIQUE,
  email VARCHAR(160) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(30) NOT NULL
);